=== hashgraph/hedera-nft-sdk/validator/schemas/HIP412@1.0.0.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"version": "1.0.0",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string",
			"description": "Identifies the asset to which this token represents."
		},
		"creator": {
			"type": "string",
			"description": "Identifies the artist name(s)."
		},
		"creatorDID": {
			"type": "string",
			"format": "uri",
			"description": "Points to a decentralized identifier to identify the creator."
		},
		"description": {
			"type": "string",
			"description": "Describes the asset to which this token represents."
		},
		"image": {
			"type": "string",
			"format": "uri",
			"description": "A URI pointing to a resource with mime type image/* representing the asset to which this token represents. Consider making any images at a width between 320 and 1080 pixels and aspect ratio between 1.91:1 and 4:5 inclusive."
		},
		"checksum": {
			"type": "string",
			"description": "Cryptographic SHA-256 hash of the representation of the 'image' resource."
		},
		"type": {
			"type": "string",
			"description": "Sets the MIME type for the 'image' resource."
		},
		"format": {
			"type": "string",
			"default": "HIP412@1.0.0",
			"description": "Name of the format or schema used by the NFT. For this schema representing Hedera Collectible NFts, set 'format' to 'HIP412@1.0.0'."
		},
		"properties": {
			"type": "object",
			"description": "Holds any arbitrary properties. Values may be strings, numbers, booleans, objects or arrays."
		},
		"files": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"type": "string",
						"format": "uri",
						"description": "A URI pointing to a resource."
					},
					"checksum": {
						"type": "string",
						"description": "Cryptographic SHA-256 hash of the representation of the 'uri' resource."
					},
					"type": {
						"type": "string",
						"description": "Sets the MIME type for the 'image' resource."
					},
					"is_default_file": {
						"type": "boolean",
						"description": "Indicates if this file object is the main file representing the NFT."
					},
					"metadata": {
						"type": "object",
						"description": "Represents a nested metadata object for the file, which follows the same metadata format as the root metadata. Files can be nested indefinitely in this way, but processed with the same metadata code."
					},
					"metadata_uri": {
						"type": "string",
						"format": "uri",
						"description": "A URI pointing to a metadata resource, which follows the same metadata format as the root metadata. Files can be nested indefinitely in this way, but processed with the same metadata code."
					}
				},
				"required": [
					"uri",
					"type"
				],
				"additionalProperties": false
			}
		},
		"attributes": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"trait_type": {
						"type": "string",
						"description": "Name of trait."
					},
					"display_type": {
						"type": "string",
						"description": "Sets the representation of the value of the trait."
					},
					"value": {
						"type": ["string", "integer", "number", "boolean"],
						"description": "Value for trait."
					},
					"max_value": {
						"type": ["string", "integer", "number"],
						"description": "Maximum value for trait."
					}
				},
				"required": [
					"trait_type",
					"value"
				],
				"additionalProperties": false
			}
		},
		"localization": {
			"type": "object",
			"required": ["uri", "default", "locales"],
			"properties": {
				"uri": {
					"type": "string",
					"description": "The URI pattern to fetch localized data from. This URI should contain the substring `{locale}` which will be replaced with the appropriate two-letter langauge code value before sending the request. Format: <protocol>://<hash>/{locale}.json"
				},
				"default": {
					"type": "string",
					"description": "Sets the two-letter language code that represents the default locale for this metadata file."
				},
				"locales": {
					"type": "array",
					"description": "The list of locales for which data is available.",
					"items": {
						"type": "string"
					}
				}
			},
			"additionalProperties": false
		}
	},
	"required": [
		"name",
		"image",
		"type"
	]
}

=== hashgraph/hedera-nft-sdk/src/test/__mocks__/json/files-with-mixed-extensions/example-4.json
{
  "name": "Example NFT 4",
  "creator": "Hedera",
  "description": "This is an example NFT 4",
  "image": "https://nft.com/mycollection/4.jpg",
  "type": "image/jpeg",
  "properties": {
    "external_url": "https://nft.com/mycollection/4",
    "url": "https://nft.com/mycollection/4"
  },
  "attributes": [
    { "trait_type": "color", "value": "rgb(0,255,0)" },
    { "trait_type": "hasPipe", "value": "false" },
    { "trait_type": "stamina", "value": "55" }
  ]
}

=== hashgraph/hedera-nft-sdk/examples/local-metadata-validator/files/nft3.json
{
    "creator": "HANGRY BARBOONS",
    "description": "HANGRY BARBOONS are 4,444 unique citizens from the United Hashgraph of Planet Earth. Designed and illustrated by President HANGRY.",
    "format": "none",
    "name": "HANGRY BARBOON #2343",
    "image": "ipfs://QmaHVnnp7qAmGADa3tQfWVNxxZDRmTL5r6jKrAo16mSd5y/2343.png",
    "type": "image/png",
    "properties": { "edition": 2343 },
    "attributes": [
      { "trait_type": "Background", "value": "Yellow" },
      { "trait_type": "Fur", "value": "Silver" },
      { "trait_type": "Clothing", "value": "Floral Jacket" },
      { "trait_type": "Mouth", "value": "Smile" },
      { "trait_type": "Sing", "value": "None" }
    ]
}

=== hashgraph/hedera-nft-sdk/examples/rarity-score-calculation/files/nft2.json
{
    "creator": "BOOBOO",
    "description": "BOOBOO desc",
    "format": "HIP412@1.0.0",
    "name": "HANGRY BARBOON #2343",
    "image": "ipfs://QmaHVnnp7qAmGADa3tQfWVNxxZDRmTL5r6jKrAo16mSd5y/2343.png",
    "type": "image/png",
    "properties": { "edition": 2343 },
    "attributes": [
      { "trait_type": "Background", "value": "Green" },
      { "trait_type": "Fur", "value": "Gold" },
      { "trait_type": "Clothing", "value": "Floral Jacket" },
      { "trait_type": "Mouth", "value": "Tongue" },
      { "trait_type": "Sing", "value": "None" }
    ]
}

=== hashgraph/hedera-nft-sdk/tests/validator/data/valid-HIP412.json
{
  "creator": "HANGRY BARBOONS",
  "description": "HANGRY BARBOONS are 4,444 unique citizens from the United Hashgraph of Planet Earth. Designed and illustrated by President HANGRY.",
  "format": "none",
  "name": "HANGRY BARBOON #2343",
  "image": "ipfs://QmaHVnnp7qAmGADa3tQfWVNxxZDRmTL5r6jKrAo16mSd5y/2343.png",
  "type": "image/png",
  "properties": { "edition": 2343 },
  "attributes": [
    { "trait_type": "Background", "value": "Yellow" },
    { "trait_type": "Fur", "value": "Gold" },
    { "trait_type": "Clothing", "value": "Floral Jacket" },
    { "trait_type": "Mouth", "value": "Tongue" },
    { "trait_type": "Eyes", "value": "Punched" },
    { "trait_type": "Eyewear", "value": "Swirls Glasses" },
    { "trait_type": "Headwear", "value": "Royal Crown" },
    { "trait_type": "Accessory", "value": "None" },
    { "trait_type": "Arm", "value": "Knife" }
  ]
}
